"""initial schema

Revision ID: c4f156fe2bc8
Revises: 
Create Date: 2026-09-17 19:16:17.578957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f156fe2bc8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('voice_description', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=False)
    op.create_table('competitor_digest_entries',
    sa.Column('competitor_url', sa.String(), nullable=False),
    sa.Column('last_snapshot_hash', sa.String(), nullable=True),
    sa.Column('suggested_action', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_digest_entries_competitor_url'), 'competitor_digest_entries', ['competitor_url'], unique=False)
    op.create_index(op.f('ix_competitor_digest_entries_id'), 'competitor_digest_entries', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('niche', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('fit_reason', sa.String(), nullable=True),
    sa.Column('draft_outreach', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'approved', name='leadstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('content_assets',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('source_asset_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'approved', 'published', name='contentstatus'), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['content_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_assets_id'), 'content_assets', ['id'], unique=False)
    op.create_table('compliance_reviews',
    sa.Column('content_asset_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('flagged_phrases', sa.JSON(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['content_asset_id'], ['content_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_reviews_id'), 'compliance_reviews', ['id'], unique=False)
    op.create_table('content_versions',
    sa.Column('content_asset_id', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['content_asset_id'], ['content_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_versions_id'), 'content_versions', ['id'], unique=False)
    op.create_table('feedback',
    sa.Column('content_asset_id', sa.Integer(), nullable=False),
    sa.Column('reason_tag', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['content_asset_id'], ['content_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_table('video_assets',
    sa.Column('content_asset_id', sa.Integer(), nullable=False),
    sa.Column('script_text', sa.String(), nullable=False),
    sa.Column('video_file_path', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['content_asset_id'], ['content_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_assets_id'), 'video_assets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_assets_id'), table_name='video_assets')
    op.drop_table('video_assets')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_content_versions_id'), table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_index(op.f('ix_compliance_reviews_id'), table_name='compliance_reviews')
    op.drop_table('compliance_reviews')
    op.drop_index(op.f('ix_content_assets_id'), table_name='content_assets')
    op.drop_table('content_assets')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_competitor_digest_entries_id'), table_name='competitor_digest_entries')
    op.drop_index(op.f('ix_competitor_digest_entries_competitor_url'), table_name='competitor_digest_entries')
    op.drop_table('competitor_digest_entries')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
